module.exports = {
  HTTP_CODE_OK: 200,
  HTTP_CODE_CREATED: 201,
  HTTP_CODE_ACCEPTED: 202,
  HTTP_CODE_BAD_REQUEST: 400,
  HTTP_CODE_UNAUTHORIZED: 401,
  HTTP_CODE_NOT_FOUND: 404,
  HTTP_CODE_INVALID_ARGUMENT: 409
}
